### ISSUE TITLE
[patch] Build broken (Linux)

### ISSUE THREAD

**Issue by ebachard** [moonyl/ffplayByCpp#1]
Hello,

First, thanks for sharing your code. I tested it, and there was a lot of issues. As you probably imagine, I didn't find the time to fix everything, but at least, the compilation ends, and the sound works (I quickly tested a local mp4 file). For the video, a lot remain to do (mostly deprecated ffmpeg API), and if I found the time, I'll continue.

Consider the attached code is under MIT license, and do what you want with it.

[ffplayCpp.diff.txt](https://github.com/moonyl/ffplayByCpp/files/2325818/ffplayCpp.diff.txt)

**Comment by moonyl** [comment]
Hello.
Above all, thank you for your interest.
I had worked in the company which did business for contents-service and
streaming. But, now I have moved to another company for block-chain. So I
am not sure that I can continue to improve the codes.
How about joining as a collaborator for it? I think that you can make the
codes valuable and I hope so.
If you wish, I want to collaborate you in order to improve the job.

2018년 8월 28일 (화) 오전 7:15, ebachard <notifications@github.com>님이 작성:

**Comment by ebachard** [comment]
Hello,

Thanks for your reactivity !

I'm testing a lot of code, because I have to solve a problem for my own code (see miniDart). So I'm testing everything around ffmpeg + SDL2 + ImGui + OpenGL and OpenCV , and when I can help, I'm glad to.  But ... I fear I can't accept your proposal : my time is very limited, and as simple volunteer, I got other projects to maintain and I must care to not manage too much  ;-) Nevertheless, I'll continue to contribute to your object, and if ever I find a solution, I'll help you to solve the remaining warnings. Please note this is difficult task, since the API has to be modified, because of obsolete ffmpeg use.

HTH

**Comment by moonyl** [comment]
The amendment was applied.
